language: php
php:
 - "5.5"
 - "5.6"
 - "hhvm"

env:
 - NIBII_DATASTORE=mysql NIBII_HOST=localhost NIBII_USER=root NIBII_DBNAME=nibii_test NIBII_PDO_DSN='mysql:host=localhost;dbname=nibii_test;user=root' NIBII_NO_SCHEMAS=yes
 - NIBII_DATASTORE=postgresql NIBII_HOST=localhost NIBII_USER=postgres NIBII_DBNAME=nibii_test NIBII_PDO_DSN='pgsql:host=localhost;dbname=nibii_test;user=postgres'


matrix:
 include:
  - php: "7"
    env: NIBII_DATASTORE=mysql NIBII_HOST=localhost NIBII_USER=root NIBII_DBNAME=nibii_test NIBII_PDO_DSN='mysql:host=localhost;dbname=nibii_test;user=root' COVERAGE=yes
  - php: "7"
    env: NIBII_DATASTORE=postgresql NIBII_HOST=localhost NIBII_USER=postgres NIBII_DBNAME=nibii_test NIBII_PDO_DSN='pgsql:host=localhost;dbname=nibii_test;user=root' COVERAGE=yes
 exclude:
  - php: "hhvm"
    env: NIBII_DATASTORE=postgresql NIBII_HOST=localhost NIBII_USER=postgres NIBII_DBNAME=nibii_test NIBII_PDO_DSN='pgsql:host=localhost;dbname=nibii_test;user=postgres'

before_script:
 - composer install --prefer-dist
 - if [ "$NIBII_DATASTORE" = "mysql" ]; then mysql -e 'create database nibii_test;'; fi
 - if [ "$NIBII_DATASTORE" = "mysql" ]; then mysql nibii_test < tests/databases/mysql.sql; fi
 - if [ "$NIBII_DATASTORE" = "postgresql" ]; then psql -c 'create database nibii_test;' -U postgres; fi
 - if [ "$NIBII_DATASTORE" = "postgresql" ]; then psql -f tests/databases/postgresql.sql -U postgres -d nibii_test; fi

services:
 - mysql
 - postgresql

script: vendor/bin/phpunit --coverage-clover coverage.clover --configuration tests/config/travis.xml
after_script: if [ "$COVERAGE" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
